FROM python:3.8-alpine


RUN apk update
RUN apk add git

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./src/start.sh /start.sh

RUN sed -i 's/\r//' /start.sh
RUN chmod +x /start.sh

COPY ./src /src
WORKDIR /src
